# Generated by Django 4.2.7 on 2023-11-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radicoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='startups',
            old_name='stratup_no',
            new_name='startup_no',
        ),
        migrations.AlterField(
            model_name='startups',
            name='startup_city',
            field=models.CharField(max_length=10),
        ),
    ]
